[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true

[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
showSidebarNavigation = true

[runner]
magicEnabled = false

